
version: '3.8'

services:
  miniclust:
    image: openmole/miniclust:latest
    container_name: miniclust
    command: --config "/config/config.yml"
    volumes:
      - config-volume:/config
    environment:
      - HOSTNAME=${HOSTNAME}
    restart: always
    privileged: true
    depends_on:
      - init
    labels:
      - com.centurylinklabs.watchtower.enable=true

  init:
    image: debian:12-slim
    entrypoint: /bin/sh -c "
      cp /run/secrets/miniclust_config /config/config.yml &&
      chmod 600 /config/config.yml &&
      chown -R 1001:1001 /config &&
      echo '[init] Initialization complete'"
    volumes:
      - config-volume:/config
    secrets:
      - miniclust_config
    user: "0"
    restart: "no"  

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_LABEL_ENABLE=true

secrets:
  miniclust_config:
    file: ./config.yml


volumes:
  config-volume:

